{{- if .Values.pd.enabled }}
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: {{ include "helm.decodeLWSName" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    component: decode
spec:
  replicas: {{ .Values.decode.replicas }}
  leaderWorkerTemplate:
    size: {{ .Values.decode.groupSize }}
    restartPolicy: {{ .Values.decode.restartPolicy }}
    leaderTemplate:
      metadata:
        labels:
          {{- include "helm.selectorLabels" . | nindent 10 }}
          component: decode
          role: leader
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        hostIPC: true
        containers:
          - name: {{ include "helm.decodeLWSName" . }}-leader
            image: {{ .Values.decode.image }}
            imagePullPolicy: {{ .Values.decode.imagePullPolicy }}
            securityContext:
              privileged: true
            {{- if .Values.decode.env }}
            env:
              {{- toYaml .Values.decode.env | nindent 14 }}
            {{- end }}
            {{- if .Values.commonEnv }}
            env:
              {{- toYaml .Values.commonEnv | nindent 14 }}
            {{- end }}
            command: ["bash", "-c"]
            args:
              - |
                python3 -m sglang.launch_server \
                  --model-path {{ .Values.model.path }} \
                  --tp {{ .Values.decode.args.tpSize }} \
                  --pp {{ .Values.decode.args.ppSize }} \
                  --dist-init-addr $(LWS_LEADER_ADDRESS):20000 \
                  --nnodes $(LWS_GROUP_SIZE) \
                  --node-rank $(LWS_WORKER_INDEX) \
                  {{- if .Values.decode.args.epEnabled }}
                  --enable-ep-moe \
                  {{- end }}
                  --trust-remote-code \
                  --host 0.0.0.0 \
                  --port {{ .Values.decode.service.port }} \
                  --mem-fraction-static {{ .Values.decode.args.memFractionStatic }} \
                  --disaggregation-mode decode \
                  --pdlb-url http://{{ include "helm.lbName" . }}:{{ .Values.loadBalancer.port }} \
                  --disaggregation-transfer-backend {{ .Values.pd.transferBackend }} \
                  --enable-deepep-moe --deepep-mode low_latency \
                  {{- range .Values.decode.args.extraArgs }}
                  {{ . }} \
                  {{- end }}
            resources:
              limits:
                nvidia.com/gpu: {{ .Values.decode.resources.gpu }}
              requests:
                nvidia.com/gpu: {{ .Values.decode.resources.gpu }}
            ports:
              - containerPort: {{ .Values.decode.service.port }}
                name: http
              - containerPort: 20000
                name: dist
            startupProbe:
              httpGet:
                path: /health
                port: {{ .Values.decode.service.port }}
                scheme: HTTP
              timeoutSeconds: 3
              periodSeconds: 10
              failureThreshold: 360
            livenessProbe:
              httpGet:
                path: /health
                port: {{ .Values.decode.service.port }}
                scheme: HTTP
              timeoutSeconds: 3
              periodSeconds: 10
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: /health
                port: {{ .Values.decode.service.port }}
                scheme: HTTP
              timeoutSeconds: 3
              periodSeconds: 10
              failureThreshold: 3
            volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            {{- if .Values.model.pvc.enabled }}
            - name: model
              mountPath: {{ .Values.model.path }}
              subPath: {{ .Values.model.pvc.path }}
            {{- else if .Values.model.local.enabled }}
            - name: model
              mountPath: {{ .Values.model.path }}
            {{- end }}
            - name: ib
              mountPath: /dev/infiniband
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 256Gi
          {{- if .Values.model.pvc.enabled }}
          - name: model
            persistentVolumeClaim:
              claimName: {{ .Values.model.pvc.name }}
          {{- else if .Values.model.local.enabled }}
          - name: model
            hostPath:
              path: {{ .Values.model.local.path }}
          {{- end }}
          - name: ib
            hostPath:
              path: /dev/infiniband
    workerTemplate:
      metadata:
        labels:
          {{- include "helm.selectorLabels" . | nindent 10 }}
          component: decode
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        hostIPC: true
        containers:
          - name: {{ include "helm.decodeLWSName" . }}-worker
            image: {{ .Values.decode.image }}
            imagePullPolicy: {{ .Values.decode.imagePullPolicy }}
            securityContext:
              privileged: true
            {{- if .Values.decode.env }}
            env:
              {{- toYaml .Values.decode.env | nindent 14 }}
            {{- end }}
            {{- if .Values.commonEnv }}
            env:
              {{- toYaml .Values.commonEnv | nindent 14 }}
            {{- end }}
            command: ["bash", "-c"]
            args:
              - |
                python3 -m sglang.launch_server \
                  --model-path {{ .Values.model.path }} \
                  --tp {{ .Values.decode.args.tpSize }} \
                  --pp {{ .Values.decode.args.ppSize }} \
                  --dist-init-addr $(LWS_LEADER_ADDRESS):20000 \
                  --nnodes $(LWS_GROUP_SIZE) \
                  --node-rank $(LWS_WORKER_INDEX) \
                  {{- if .Values.decode.args.epEnabled }}
                  --enable-ep-moe \
                  {{- end }}
                  --trust-remote-code \
                  --host 0.0.0.0 \
                  --port {{ .Values.decode.service.port }} \
                  --mem-fraction-static {{ .Values.decode.args.memFractionStatic }} \
                  --disaggregation-mode decode \
                  --disaggregation-transfer-backend {{ .Values.pd.transferBackend }} \
                  --enable-deepep-moe --deepep-mode low_latency \
                  {{- range .Values.decode.args.extraArgs }}
                  {{ . }} \
                  {{- end }}
            resources:
              limits:
                nvidia.com/gpu: {{ .Values.decode.resources.gpu }}
              requests:
                nvidia.com/gpu: {{ .Values.decode.resources.gpu }}
            volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            {{- if .Values.model.pvc.enabled }}
            - name: model
              mountPath: {{ .Values.model.path }}
              subPath: {{ .Values.model.pvc.path }}
            {{- else if .Values.model.local.enabled }}
            - name: model
              mountPath: {{ .Values.model.path }}
            {{- end }}
            - name: ib
              mountPath: /dev/infiniband
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 256Gi
          {{- if .Values.model.pvc.enabled }}
          - name: model
            persistentVolumeClaim:
              claimName: {{ .Values.model.pvc.name }}
          {{- else if .Values.model.local.enabled }}
          - name: model
            hostPath:
              path: {{ .Values.model.local.path }}
          {{- end }}
          - name: ib
            hostPath:
              path: /dev/infiniband
{{- end }}