# 全局配置
global:
  name: sglang
  # namespace: default

# LeaderWorkerSet 配置
leaderWorkerSet:
  replicas: 1
  size: 2
  restartPolicy: RecreateGroupOnPodRestart

# 镜像配置
image:
  repository: lmsysorg/sglang
  tag: latest
  pullPolicy: IfNotPresent

# 模型配置
model:
  hostPath: "/data/models"  # 主机模型路径
  mountPath: "/work/models" # 容器挂载路径

# 资源分配
resources:
  leader:
    gpu: 8
    cpu: 0
    memory: 0
  worker:
    gpu: 8
    cpu: 0
    memory: 0

# SGLang 服务器配置
sglang:
  # 通用参数
  memFractionStatic: 0.93
  torchCompileMaxBs: 8
  maxRunningRequests: 20
  tensorParallelism: 16
  trustRemoteCode: true
  
  # Leader 专用参数
  leader:
    host: 0.0.0.0
    port: 40000
    
  # 网络配置
  distInitPort: 20000

  # NCCL/RDMA配置
  ncclIBCudaSupport: 1
  ncclIBDisable: 0
  ncclIbGidIndex: 3
  ncclSocketIfname: eth0
  ncclDebug: INFO

  # gloo
  glooSocketIfname: eth0
  
# 网络配置
network:
  hostNetwork: true
  hostIPC: true
  dnsPolicy: ClusterFirstWithHostNet

# 共享内存配置
sharedMemory:
  enabled: true
  size: 32G

# 服务配置
service:
  enabled: true
  name: sglang-leader
  type: ClusterIP
  port: 40000
  targetPort: 40000

commandStr: |
  python3 -m sglang.launch_server \
    --model-path {{ .Values.model.mountPath }} \
    --mem-fraction-static "{{ .Values.sglang.memFractionStatic }}" \
    --torch-compile-max-bs "{{ .Values.sglang.torchCompileMaxBs }}" \
    --max-running-requests "{{ .Values.sglang.maxRunningRequests }}" \
    --tp "{{ .Values.sglang.tensorParallelism }}" \
    --dist-init-addr $(LWS_LEADER_ADDRESS):{{ .Values.sglang.distInitPort }} \
    --nnodes $(LWS_GROUP_SIZE) \
    --node-rank $(LWS_WORKER_INDEX) \
    --trust-remote-code \
    --port "{{ .Values.sglang.leader.port }}"

env: |
  - name: NCCL_IB_CUDA_SUPPORT
    value: "{{ .Values.sglang.ncclIBCudaSupport }}"
  - name: NCCL_IB_DISABLE
    value: "{{ .Values.sglang.ncclIBDisable }}"
  - name: NCCL_IB_GID_INDEX
    value: "{{ .Values.sglang.ncclIbGidIndex }}"
  - name: NCCL_DEBUG
    value: "{{ .Values.sglang.ncclDebug }}"
  - name: GLOO_SOCKET_IFNAME
    value: "{{ .Values.sglang.glooSocketIfname }}"
  - name: NCCL_SOCKET_IFNAME
    value: "{{ .Values.sglang.ncclSocketIfname }}"


volumes: |
  - name: dshm
    emptyDir:
      medium: Memory
        sizeLimit: {{ .Values.sharedMemory.size }}
  - name: model
    hostPath:
      path: {{ .Values.model.hostPath }}
  - name: ib
    hostPath:
      path: /dev/infiniband

volumeMounts: | 
  - name: dshm
    mountPath: /dev/shm  
  - name: model
    mountPath: {{ .Values.model.mountPath }}
  - name: ib
    mountPath: /dev/infiniband

workerResourcesStr: |
  limits:
    nvidia.com/gpu: "{{ .Values.resources.worker.gpu }}"
    cpu: "{{ .Values.resources.worker.cpu }}"
    memory: "{{ .Values.resources.worker.memory }}"

leaderResourcesStr: |
  limits:
    nvidia.com/gpu: "{{ .Values.resources.leader.gpu }}"
    cpu: "{{ .Values.resources.leader.cpu }}"
    memory: "{{ .Values.resources.leader.memory }}"