apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.leaderWorkerSet.replicas }}
  leaderWorkerTemplate:
    size: {{ .Values.leaderWorkerSet.size }}
    restartPolicy: {{ .Values.leaderWorkerSet.restartPolicy }}
    leaderTemplate:
      metadata:
        labels:
          role: leader
      spec:
        dnsPolicy: {{ .Values.network.dnsPolicy }}
        hostNetwork: {{ .Values.network.hostNetwork }}
        hostIPC: {{ .Values.network.hostIPC }}
        containers:
          - name: sglang-leader
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            securityContext:
              privileged: true
            env:
              {{- tpl .Values.env . | nindent 14 }}
            command: ["/bin/sh", "-c"]
            args:
              - | {{ tpl .Values.commandStr . | nindent 16 }}
            resources:
              {{- tpl .Values.leaderResourcesStr . | nindent 14 }}
            ports:
              - containerPort: {{ .Values.sglang.leader.port }}
            readinessProbe:
              tcpSocket:
                port: {{ .Values.sglang.leader.port }}
              initialDelaySeconds: 30
              periodSeconds: 10
            volumeMounts:
              {{- tpl .Values.volumeMounts . | nindent 14 }}
        volumes:
          {{- if .Values.sharedMemory.enabled }}
          - name: dshm
            emptyDir:
              medium: Memory
              {{- if .Values.sharedMemory.size }}
              sizeLimit: {{ .Values.sharedMemory.size }}
              {{- end }}
          {{- end }}
          - name: ib
            hostPath:
              path: /dev/infiniband
          - name: model
            hostPath:
              path: {{ .Values.model.hostPath }}
    workerTemplate:
      spec:
        dnsPolicy: {{ .Values.network.dnsPolicy }}
        hostNetwork: {{ .Values.network.hostNetwork }}
        hostIPC: {{ .Values.network.hostIPC }}
        containers:
          - name: sglang-worker
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            securityContext:
              privileged: true
            env:
              {{- tpl .Values.env . | nindent 14 }}
            command: ["/bin/sh", "-c"]
            args:
              - | {{ tpl .Values.commandStr . | nindent 16 }}
            resources:
              {{- tpl .Values.workerResourcesStr . | nindent 14 }}
            volumeMounts:
              {{- tpl .Values.volumeMounts . | nindent 14 }}
        volumes:
          {{- if .Values.sharedMemory.enabled }}
          - name: dshm
            emptyDir:
              medium: Memory
              {{- if .Values.sharedMemory.size }}
              sizeLimit: {{ .Values.sharedMemory.size }}
              {{- end }}
          {{- end }}
          - name: ib
            hostPath:
              path: /dev/infiniband
          - name: model
            hostPath:
              path: {{ .Values.model.hostPath }}