{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    leaderworkerset.sigs.k8s.io/name: {{ .Values.global.name }}
    role: leader
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
{{- end }}