apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: model-pressure-test-
  namespace: default
spec:
  entrypoint: main
  serviceAccountName: model-test-runner
  volumes:
  - name: scripts
    configMap:
      name: workflow-scripts
      defaultMode: 0755
  - name: shared-pvc
    persistentVolumeClaim:
      claimName: charts-pvc  # 保存 helm chart 
  - name: dataset-pvc
    persistentVolumeClaim:
      claimName: custom-dataset-pvc
  - name: model-pvc-map
    configMap:
      name: model-pvc-config  # 提供模型到pvc的映射关系
  - name: test-parameters-config # 定义测试参数
    configMap:
      name: test-parameters-config

  arguments:
    parameters:
    - name: chart_path
      value: "/shared-data/helm-chart"
    - name: model_timeout
      value: "1800"  # 模型部署超时时间（秒）如果开启torch编译会更耗时
    - name: test_timeout
      value: "7200"  # 测试超时时间（秒）
    - name: max_retries
      value: "0"  # 最大重试次数

  parallelism: 1
  templates:
  - name: main
    steps:
    - - name: generate-test-matrix
        templateRef:
          name: genrate-config
          template: genrate-config
          clusterScope: true
    - - name: run-all-tests
        template: test-loop
        arguments:
          parameters:
          - name: test_config
            value: "{{item}}"
        withParam: "{{steps.generate-test-matrix.outputs.parameters.configs}}"

  # 测试循环模板
  - name: test-loop
    inputs:
      parameters:
      - name: test_config
    retryStrategy:
      limit: "{{workflow.parameters.max_retries}}"
      retryPolicy: "Always"
    dag:
      tasks:
      - name: deploy-model
        templateRef:
          name: deploy-model
          template: deploy-model
          clusterScope: true
        arguments:
          parameters:
          - name: config
            value: "{{inputs.parameters.test_config}}"
          - name: chart_path
            value: "{{workflow.parameters.chart_path}}"
          - name: model_timeout
            value: "{{workflow.parameters.model_timeout}}"
          - name: max_retries
            value: "{{workflow.parameters.max_retries}}"
      - name: run-pressure-test
        dependencies: [deploy-model]
        templateRef:
          name: pressure-test-operator
          template: pressure-test
          clusterScope: true
        arguments:
          parameters:
          - name: configs_json
            value: "{{inputs.parameters.test_config}}"
          - name: values_yaml
            value: "{{tasks.deploy-model.outputs.parameters.values_yaml}}"
          - name: pre_status
            value: "{{tasks.deploy-model.outputs.parameters.status_code}}"
          - name: release_name
            value: "{{tasks.deploy-model.outputs.parameters.release_name}}"
        hooks:
          exit:
            template: cleanup
            arguments:
              parameters:
              - name: release_name
                value: "{{tasks.deploy-model.outputs.parameters.release_name}}"

  - name: cleanup
    inputs:
      parameters:
      - name: release_name
    steps:
    - - name: call-cleanup-operator
        templateRef:
          name: cleanup-operator
          template: cleanup-resources
          clusterScope: true
        arguments:
          parameters:
          - name: release_name
            value: "{{inputs.parameters.release_name}}"
          - name: namespace
            value: "{{workflow.namespace}}"
          - name: cleanup_strategy
            value: "aggressive"
          - name: delete_pvcs
            value: "false"
