apiVersion: v1
kind: Pod
metadata:
  name: pvc-checker
spec:
  containers:
  - name: checker
    image: alpine:3.18
    command: ["sh", "-c", "sleep 3600"]  # 保持容器运行
    volumeMounts:
    - name: shared-data  # 挂载到容器内的路径
      mountPath: /shared-data
  volumes:
  - name: shared-data
    persistentVolumeClaim:
      claimName: charts-pvc  # 指定 PVC 名称