---
# 功能说明: 部署模型
# 参数说明:
#   deploy-model 模板参数说明:
#
# 输出:
#   release_name:
#   status_code:
# 详细说明:
#   根据配置参数部署模型
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: deploy-model
spec:
  entrypoint: deploy-model
  arguments:
    parameters:
    - name: config
    - name: chart_path
    - name: model_timeout
    - name: max_retries
  templates:
  - name: deploy-model
    inputs:
      parameters:
      - name: config
      - name: chart_path
      - name: model_timeout
      - name: max_retries
    outputs:
      parameters:
      - name: release_name
        valueFrom:
          path: /tmp/release_name
      - name: status_code
        valueFrom:
          path: /tmp/status_code
      - name: values_yaml
        valueFrom:
          path: /tmp/values.yaml
    retryStrategy:
      limit: "{{inputs.parameters.max_retries}}"
      retryPolicy: "OnFailure"
    container:
      image: alpine/k8s:1.30.14 
      command: [python, /scripts/deploy_model.py]
      env:
        - name: CONFIG_JSON
          value: "{{inputs.parameters.config}}"
        - name: CHART_PATH
          value: "{{inputs.parameters.chart_path}}"
        - name: MODEL_TIMEOUT
          value: "{{inputs.parameters.model_timeout}}"
        - name: ARGO_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumeMounts:
      - name: scripts
        mountPath: /scripts
      - name: shared-pvc
        mountPath: /shared-data
      - name: model-pvc-map
        mountPath: /etc/config/model-pvc-map
