apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: pressure-test-operator
spec:
  entrypoint: pressure-test
  arguments:
    parameters:
    - name: pre_status
    - name: configs_json
    - name: release_name
    - name: values_yaml
  
  templates:
  - name: pressure-test
    inputs:
      parameters:
      - name: configs_json
      - name: pre_status
      - name: release_name
      - name: values_yaml
    outputs:
      parameters:
      - name: status_code
        valueFrom:
          path: /tmp/status_code

    script:
      image: fanjiankong-bj.tencentcloudcr.com/pengdrumli/launch-evalscpoe-perf:v0.1
      command: [python, /scripts/pressure_test_operator.py]
      env:
        - name: RELEASE_NAME
          value: "{{inputs.parameters.release_name}}"
        - name: CONFIGS_JSON
          value: "{{inputs.parameters.configs_json}}"
        - name: PRE_STATUS
          value: "{{inputs.parameters.pre_status}}"
        - name: VALUES_YAML
          value: "{{inputs.parameters.values_yaml}}"
      volumeMounts:
      - name: scripts
        mountPath: /scripts
      - name: shared-pvc
        mountPath: /shared-data
      - name: model-pvc-map
        mountPath: /etc/config/model-pvc-map
      - name: test-parameters-config
        mountPath: /etc/test-parameters
      - name: dataset-pvc
        mountPath: /dataset