apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: pressure-test-operator
spec:
  entrypoint: pressure-test
  arguments:
    parameters:
    - name: pre_status
    - name: configs_json
  
  templates:
  - name: pressure-test
    inputs:
      parameters:
      - name: configs_json
      - name: pre_status
    outputs:
      parameters:
      - name: status_code
        valueFrom:
          path: /tmp/status_code
      # - name: report_path
      #   valueFrom:
      #     path: /tmp/report_path
    script:
      image: fanjiankong-bj.tencentcloudcr.com/pengdrumli/evalscpoe-perf:v0.5
      command: [python]
      source: |
        import os
        import json
        import sys
        import time
        from evalscope.perf.main import run_perf_benchmark
        from evalscope.perf.arguments import Arguments

        CONFIG_MAP_MODEL_PVC_PATH = "/etc/test-parameters"
        def read_param_from_model_pvc_map(param_name, default_value=''):
            file_path = os.path.join(CONFIG_MAP_MODEL_PVC_PATH, param_name)
            if os.path.exists(file_path):
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        content = f.read().strip()
                        return content if content else default_value
                except Exception as e:
                    print(f"Error reading {file_path}: {e}. Returning default value.")
                    return default_value
            return default_value
        
        configs_json_str = '{{inputs.parameters.configs_json}}'
        pre_status = "{{inputs.parameters.pre_status}}"

        with open("/tmp/status_code", "w") as f:
            f.write("false")
        if pre_status.lower() == 'false':
            print("pre_status 为 false，跳过性能测试。")
            sys.exit(0) # 正常退出脚本，Argo Workflow 任务将完成


        config = json.loads(configs_json_str)
        deployment_cfg = config.get("deployment", {})
        test_cfg = config.get("test", {})

        name = deployment_cfg.get("name")
        model = deployment_cfg.get("model", "default-model") # 使用部署模型
        tokenizer = test_cfg.get("tokenizer", model) # 使用测试 tokenizer，如果没有则回退到部署模型
        dataset = test_cfg.get("dataset", "random")
        dataset_path = test_cfg.get("dataset_path", "")
        isl = test_cfg.get("ISL")
        osl = test_cfg.get("OSL")
        tp = deployment_cfg.get("tp")
        dp = deployment_cfg.get("dp")
        ep = deployment_cfg.get("ep")
        # pd = deployment_cfg.get("pd")
        engine = deployment_cfg.get("engine")
        node_size = deployment_cfg.get("node_size")

        eos = str(test_cfg.get("EOS", True)) # 确保它是字符串以便比较
        service = test_cfg.get("service", "127.0.0.1")
        service_port = test_cfg.get("service_port", 8801)

        ignore_eos = True if eos.lower() == 'false' else False
        url = f"http://{service}:{service_port}/v1/chat/completions"

        DB_HOST = read_param_from_model_pvc_map('db_host', default_value=os.getenv('DB_HOST', ''))
        DB_PORT = read_param_from_model_pvc_map('db_port', default_value=os.getenv('DB_PORT', ''))
        DB_NAME = read_param_from_model_pvc_map('db_name', default_value=os.getenv('DB_NAME', ''))
        DB_USER = read_param_from_model_pvc_map('db_user', default_value=os.getenv('DB_USER', ''))
        DB_PASS = read_param_from_model_pvc_map('db_password', default_value=os.getenv('DB_PASS', ''))

        # Initialize Arguments with common parameters
        task_cfg_args = Arguments(
            parallel=[1, 10, 16, 32, 50, 64, 100, 128, 200],
            number=[10, 20, 160, 160, 200, 320, 300, 384, 400],
            model=model,
            url=url,
            api='openai',
            tokenizer_path=model,
            extra_args={'ignore_eos': ignore_eos},
            name=name,
            metadata=name,
            tp=tp,
            dp=dp,
            ep=ep,
            engine=engine,
            node_size=node_size,
            enable_database_push=True,
            db_host=DB_HOST,
            db_port=DB_PORT,
            db_name=DB_NAME,
            db_user=DB_USER,
            db_password=DB_PASS,
            db_table_name='llm_perf',
        )

        if dataset == 'random':
            # For random dataset, ISL corresponds to max_prompt_length and min_prompt_length
            # OSL corresponds to min_tokens and max_tokens
            # dataset_path is not used
            task_cfg_args.dataset = 'random'
            task_cfg_args.min_prompt_length = int(isl)
            task_cfg_args.max_prompt_length = int(isl)
            task_cfg_args.min_tokens = int(osl)
            task_cfg_args.max_tokens = int(osl)
        elif dataset == 'custom':
            # For custom dataset, dataset_path is used, and ISL is not applicable
            task_cfg_args.dataset = 'custom'
            task_cfg_args.dataset_path = '/dataset/' + dataset_path
            task_cfg_args.min_tokens = int(osl)
            task_cfg_args.max_tokens = int(osl)
        else:
            raise ValueError(f"Unsupported dataset type: {dataset}. Must be 'random' or 'custom'.")

        # task_cfg = Arguments(**task_cfg_args)
        results = run_perf_benchmark(task_cfg_args)
        with open("/tmp/status_code", "w") as f:
            f.write("true")

      volumeMounts:
      - name: shared-pvc
        mountPath: /shared-data
      - name: model-pvc-map
        mountPath: /etc/config/model-pvc-map
      - name: test-parameters-config
        mountPath: /etc/test-parameters
      - name: dataset-pvc
        mountPath: /dataset