apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: wait-resource-operator
spec:
  entrypoint: wait-for-resource
  arguments:
    parameters:
    - name: resource_type
    - name: resource_name
    - name: timeout
    - name: pre_status
    - name: namespace
      value: "default"
  
  templates:
  - name: wait-for-resource
    inputs:
      parameters:
      - name: resource_type
      - name: resource_name
      - name: timeout
      - name: pre_status
      - name: namespace
        value: "default"
    outputs:
      parameters:
      - name: status_code
        valueFrom:
          path: /tmp/status_code
    container:
      image: bitnami/kubectl:latest
      command: [sh, /scripts/wait_for_resource.sh]
      env:
        - name: RESOURCE_TYPE
          value: "{{inputs.parameters.resource_type}}"
        - name: RESOURCE_NAME
          value: "{{inputs.parameters.resource_name}}"
        - name: TIMEOUT
          value: "{{inputs.parameters.timeout}}"
        - name: PRE_STATUS
          value: "{{inputs.parameters.pre_status}}"
        - name: NAMESPACE
          value: "{{inputs.parameters.namespace}}"
      volumeMounts:
      - name: scripts
        mountPath: /scripts