# Default values for sglang-multi.

# LeaderWorkerSet Configuration
leaderWorkerSet:
  replicas: 1
  restartPolicy: None # RecreateGroupOnPodRestart

# Model Configuration
model:
  name: "ZhipuAI/GLM-4.5"
  pvc:
    enabled: false
    name: "ai-model"
    path: "ZhipuAI/GLM-4.5"
  local:
    enabled: true
    path: "/data0/ZhipuAI/GLM-4.5"
  
# Multi-Node Deployment Configuration
multiNode:
  groupSize: 2

# SGLang Server Arguments
server:
  replicas: 1
  restartPolicy: None # RecreateGroupOnPodRestart
  image: "fanjiankong-bj.tencentcloudcr.com/pengdrumli/sglang:0.4.9.latest.v3"
  imagePullPolicy: Always
  resources:
    gpu: 8
  args:
    tpSize: 8
    ppSize: 2
    epEnabled: false
    memFractionStatic: 0.80
    trustRemoteCode: true
  extraArgs:
    - "--tool-call-parser glm45"
    - "--reasoning-parser glm45"
    - "--speculative-algorithm EAGLE"
    - "--speculative-num-steps 3"
    - "--speculative-eagle-topk 1"
    - "--speculative-num-draft-tokens 4"

  # Environment variables
  env:
    - name: NCCL_IB_CUDA_SUPPORT
      value: "1"
    - name: NCCL_IB_DISABLE
      value: "0"
    - name: NCCL_IB_GID_INDEX
      value: "3"
    - name: NCCL_DEBUG
      value: INFO
    - name: GLOO_SOCKET_IFNAME
      value: eth0
    - name: NCCL_SOCKET_IFNAME
      value: eth0

# Service Configuration
service:
  enabled: true
  type: LoadBalancer
  port: 60000