# Default values for sglang-multi.

# LeaderWorkerSet Configuration
leaderWorkerSet:
  replicas: 1
  restartPolicy: None # RecreateGroupOnPodRestart

# Model Configuration
model:
  name: "deepseek-ai/DeepSeek-V3-0324"
  pvc:
    enabled: false
    name: "default-model-pvc"
    path: ""
  local:
    enabled: true
    path: "/data0/deepseek-ai/DeepSeek-V3-0324"
  
# Multi-Node Deployment Configuration
multiNode:
  groupSize: 2

# SGLang Server Arguments
server:
  replicas: 1
  restartPolicy: None # RecreateGroupOnPodRestart
  # image: "ccr.ccs.tencentyun.com/tke-ai-playbook/sglang:nightly"
  image: "fanjiankong-bj.tencentcloudcr.com/pengdrumli/sglang:v0.4.8-cu126"
  imagePullPolicy: IfNotPresent
  resources:
    gpu: 8
  args:
    tpSize: 16
    ppSize: 1
    epEnabled: false
    memFractionStatic: 0.80
    trustRemoteCode: true
  extraArgs:

  # Environment variables
  env:
    - name: NCCL_IB_CUDA_SUPPORT
      value: "1"
    - name: NCCL_IB_DISABLE
      value: "0"
    - name: NCCL_IB_GID_INDEX
      value: "3"
    - name: NCCL_DEBUG
      value: INFO
    - name: GLOO_SOCKET_IFNAME
      value: eth0
    - name: NCCL_SOCKET_IFNAME
      value: eth0

# Service Configuration
service:
  enabled: true
  type: LoadBalancer
  port: 60000