apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicas }}
  leaderWorkerTemplate:
    size: {{ .Values.multiNode.groupSize }}
    restartPolicy: {{ .Values.leaderWorkerSet.restartPolicy }}
    leaderTemplate:
      metadata:
        labels:
          {{- include "helm.selectorLabels" . | nindent 10 }}
          role: leader
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        hostIPC: true
        containers:
          - name: {{ include "helm.fullname" . }}-leader
            image: {{ .Values.server.image }}
            imagePullPolicy: {{ .Values.server.pullPolicy }}
            securityContext:
              privileged: true
            {{- if $.Values.server.env }}
            env:
              {{- toYaml .Values.server.env | nindent 14 }}
            {{- end }}
            command: ["bash", "-c"]
            args:
              - |
                python3 -m sglang.launch_server \
                  --model-path /{{ .Values.model.name }} \
                  --tp {{ .Values.server.args.tpSize }} \
                  --pp {{ .Values.server.args.ppSize }} \
                  --dist-init-addr $(LWS_LEADER_ADDRESS):20000 \
                  --nnodes $(LWS_GROUP_SIZE) \
                  --node-rank $(LWS_WORKER_INDEX) \
                  {{- if .Values.server.args.epEnabled }}
                  --enable-ep-moe \
                  {{- end }}
                  --trust-remote-code \
                  --host 0.0.0.0 \
                  --port 60000 \
                  --mem-fraction-static {{ .Values.server.args.memFractionStatic}} \
                  {{- range .Values.server.args.extraArgs }}
                  {{ . }} \
                  {{- end }}
            resources:
              limits:
                nvidia.com/gpu: {{ .Values.server.resources.gpu }}
              requests:
                nvidia.com/gpu: {{ .Values.server.resources.gpu }}
            ports:
              - containerPort: 60000
              - containerPort: 20000
            startupProbe:
              httpGet:
                path: /health
                port: 60000
                scheme: HTTP
              timeoutSeconds: 3
              periodSeconds: 10
              failureThreshold: 360
            livenessProbe:
              httpGet:
                path: /health
                port: 60000
                scheme: HTTP
              timeoutSeconds: 3
              periodSeconds: 10
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: /health
                port: 60000
                scheme: HTTP
              timeoutSeconds: 3
              periodSeconds: 10
              failureThreshold: 3
            volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            {{- if .Values.model.pvc.enabled }}
            - name: model
              mountPath: /{{ .Values.model.name }}
              subPath: {{ .Values.model.pvc.path }}
            {{- else if .Values.model.local.enabled }}
            - name: model
              mountPath: /{{ .Values.model.name }}
            {{- end }}
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 256Gi
          {{- if .Values.model.pvc.enabled }}
          - name: model
            persistentVolumeClaim:
              claimName: {{ .Values.model.pvc.name }}
          {{- else if .Values.model.local.enabled }}
          - name: model
            hostPath:
              path: {{ .Values.model.local.path }}
          {{- end }}
    workerTemplate:
      metadata:
        labels:
          {{- include "helm.selectorLabels" . | nindent 10 }}
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        hostIPC: true
        containers:
          - name: {{ include "helm.fullname" . }}-worker
            image: {{ .Values.server.image }}
            imagePullPolicy: {{ .Values.server.pullPolicy }}
            securityContext:
              privileged: true
            {{- if .Values.server.env }}
            env:
              {{- toYaml .Values.server.env | nindent 14 }}
            {{- end }}
            command: ["bash", "-c"]
            args:
              - |
                python3 -m sglang.launch_server \
                  --model-path /{{ .Values.model.name }} \
                  --tp {{ .Values.server.args.tpSize }} \
                  --pp {{ .Values.server.args.ppSize }} \
                  --dist-init-addr $(LWS_LEADER_ADDRESS):20000 \
                  --nnodes $(LWS_GROUP_SIZE) \
                  --node-rank $(LWS_WORKER_INDEX) \
                  {{- if .Values.server.args.epEnabled }}
                  --enable-ep-moe \
                  {{- end }}
                  --trust-remote-code \
                  --host 0.0.0.0 \
                  --port 60000 \
                  --mem-fraction-static 0.8 \
                  {{- range .Values.server.args.extraArgs }}
                  {{ . }} \
                  {{- end }}
            resources:
              limits:
                nvidia.com/gpu: "{{ .Values.server.resources.gpu }}"
              requests:
                nvidia.com/gpu: "{{ .Values.server.resources.gpu }}"
            volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            {{- if .Values.model.pvc.enabled }}
            - name: model
              mountPath: /{{ .Values.model.name }}
              subPath: {{ .Values.model.pvc.path }}
            {{- else if .Values.model.local.enabled }}
            - name: model
              mountPath: /{{ .Values.model.name }}
            {{- end }}
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 256Gi
          {{- if .Values.model.pvc.enabled }}
          - name: model
            persistentVolumeClaim:
              claimName: {{ .Values.model.pvc.name }}
          {{- else if .Values.model.local.enabled }}
          - name: model
            hostPath:
              path: {{ .Values.model.local.path }}
          {{- end }}

