
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 60000
  selector:
    leaderworkerset.sigs.k8s.io/name: {{ include "helm.fullname" . }}
    role: leader
  type: {{ .Values.service.type }}
{{- end }}