{{- if .Values.pd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.prefillName" . }}-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    component: prefill
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.prefill.service.port }}
      targetPort: {{ .Values.prefill.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    component: prefill
{{- end }}