# 用于为 workflow 提供模型文件到pvc的映射关系
# namespace要和workflow保持一致

apiVersion: v1
kind: ConfigMap
metadata:
  name: model-pvc-config
  namespace: default
data:
  # key 是模型名称，value 是 PVC 名称
  Qwen3-32B: qwen3-32b-pvc
  DeepSeek-V3-0324: deepseek-v3-0324-pvc
  DeepSeek-R1: deepseek-pvc
  DeepSeek-R1-0528: deepseek-pvc