apiVersion: v1
kind: ConfigMap
metadata:
  name: test-parameters-config
  namespace: default
data:
  # ======================================================
  #         Cluster & Hardware Configuration
  # ======================================================
  node_size: '1'
  gpu_per_node: '8'
  gpu_info: "H20-96G"

  # ======================================================
  #               Model & Engine Selection
  # ======================================================
  models: '["Qwen/Qwen3-32B"]' # Models to test. , "deepseek-ai/DeepSeek-V3-0324"
  engines: '["sglang"]' # Inference engines to test

  # ======================================================
  #        Inference Configuration Switches
  # ======================================================
  # List of booleans to control whether to generate configs
  # for Pipeline Disaggregation (PD) mode.
  pd_enable: '[false]' # , true
  ep_enable: '[false]'
  pvc_enable: 'false'
    # model_basename + '_PVC'
  DeepSeek-V3-0324_PVC: 'pvc-for-deepseek-v3'
  local_enable: 'true'
  local_path: '/data0/'
  Qwen3-32B_local: '/data0/Qwen/Qwen3-32B'

  # ======================================================
  #      PD (Pipeline Disaggregation) Parameters
  # These are only used when a 'pd_enable: true' config is generated.
  # The script will scale replicas to maximize GPU usage.
  # ======================================================
  pd_prefill_replicas: '1' # Base replica count for prefill stage
  pd_decode_replicas: '1'  # Base replica count for decode stage
  pd_prefill_tp: '8'
  pd_decode_tp: '8'
  pd_prefill_pp: '1'
  pd_decode_pp: '1'

  # ======================================================
  #               Test Load Parameters
  # ======================================================
  ISL: '2000'
  OSL: '500'
  EOS: 'true'
  requests: '5'
  concurrency: '[1, 2, 4, 16, 32, 40, 64, 80, 100, 128, 150, 200]'

  # ======================================================
  #               Dataset Configuration
  # ======================================================
  dataset: 'random' # Type of dataset ('random' or 'custom')
  dataset_path: 'prompts.jsonl' # Path to custom dataset file if used

  # ======================================================
  #      (Optional) Fields for other scripts
  # These are not used by generate-config.py but can be kept for other purposes
  # ======================================================
  # service: '"llm-service-endpoint"'
  # service_port: '40000'
  # db_host: "129.226.53.35"
  # db_port: '3306'


  db_host: "127.0.0.1"
  db_port: '3306'
  db_name: "db"
  db_user: "user"
  db_password: "pass"
  db_table: "workflow-test"