apiVersion: v1
kind: ConfigMap
metadata:
  name: test-parameters-config
  namespace: default # 确保与工作流命名空间一致
data:
  models: '["Qwen/Qwen3-32B"]' # , "deepseek-ai/DeepSeek-V3-0324", "deepseek-ai/DeepSeek-R1-0528"
  engines: '["sglang"]' # , "vllm"
  node_size: '[1]'
  gpu_per_node: '[8]' 
  tp: '[8]'
  ISL: '0'
  OSL: '250'
  concurrency: '"1 4 16 32 64 128"'
  MOE: 'true'
  ep: '[2, 4, 8, 16, 1]'
  dp: '[1]'
  dp_attention: 'false'
  EOS: 'true'
  dataset: '"custom"'
  dataset_path: '"agent-format.jsonl"'
  service: '"llm-service-endpoint"'
  service_port: '40000'

  # 注意：这里的值是纯字符串，不是JSON。
  # 因为这些值是直接读取文件内容，所以不需要额外的JSON解析
  swanlab_api_key: "your-swanlab_api_key"
  swanlab_host: "http://your-swanlab_host:8000"
  useCustomDataset: 'true'
  customDatasetPath: "agent-format.jsonl" # 数据集在独立PVC上的完整路径
  customDatasetPvcName: "custom-dataset-pvc" # 独立数据集PVC的名称