apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: {{ include "sglang.fullname" . }}
  labels:
    {{- include "sglang.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.leaderWorkerSet.replicas }}
  leaderWorkerTemplate:
    size: {{ .Values.nodeSize }}
    restartPolicy: {{ .Values.leaderWorkerSet.restartPolicy }}
    leaderTemplate:
      metadata:
        labels:
          role: leader
      spec:
        dnsPolicy: {{ .Values.network.dnsPolicy }}
        hostNetwork: {{ .Values.network.hostNetwork }}
        hostIPC: {{ .Values.network.hostIPC }}
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        containers:
          - name: {{ include "sglang.fullname" . }}-leader
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            # restartPolicy: {{ .Values.restartPolicy }}
            securityContext:
              privileged: true
            env:
              {{- tpl .Values.envStr . | nindent 14 }}
            command: ["/bin/sh", "-c"]
            args:
              - | {{ tpl .Values.commandStr . | nindent 16 }}
            resources:
              {{- tpl .Values.ResourcesStr . | nindent 14 }}
            ports:
              - containerPort: {{ .Values.llmConfig.leader.port }}
            livenessProbe:
              {{- tpl .Values.livenessProbeStr . | nindent 14}}
            readinessProbe:
              {{- tpl .Values.readinessProbeStr . | nindent 14}}
            volumeMounts:
              {{- tpl .Values.volumeMounts . | nindent 14 }}
        volumes:
          {{- tpl .Values.volumes . | nindent 10 }}
        {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    workerTemplate:
      spec:
        dnsPolicy: {{ .Values.network.dnsPolicy }}
        hostNetwork: {{ .Values.network.hostNetwork }}
        hostIPC: {{ .Values.network.hostIPC }}
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        containers:
          - name: {{ include "sglang.fullname" . }}-worker
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            # restartPolicy: {{ .Values.restartPolicy }}
            securityContext:
              privileged: true
            env:
              {{- tpl .Values.envStr . | nindent 14 }}
            command: ["/bin/sh", "-c"]
            args:
              - | {{ tpl .Values.commandStr . | nindent 16 }}
            resources:
              {{- tpl .Values.ResourcesStr . | nindent 14 }}
            volumeMounts:
              {{- tpl .Values.volumeMounts . | nindent 14 }}
        volumes:
          {{- tpl .Values.volumes . | nindent 10 }}
                {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
