# LeaderWorkerSet 配置
leaderWorkerSet:
  replicas: 1
  restartPolicy: RecreateGroupOnPodRestart

restartPolicy: Always

# 镜像配置
image:
  repository: fanjiankong-bj.tencentcloudcr.com/pengdrumli/sglang
  tag: v0.4.8-cu126
  pullPolicy: IfNotPresent

# 模型配置
model:
  name: "deepseek-ai/DeepSeek-V3-0324"
  pvc:
    enabled: false
    pvcName: "default-model-pvc"
    path: ""
  local:
    enabled: true
    path: "/data0/deepseek-ai/DeepSeek-V3-0324"


# 节点
nodeSize: 2

# 资源分配
resourcesPerNode:
  gpu: 8
  cpu: 0
  memory: 0
  # 共享内存配置
  sharedMemory: 256G


# SGLang 启动配置
llmConfig:
  # 通用参数
  memFractionStatic: 0.85   # 显存预留比例
  tp: 8
  trustRemoteCode: true
  dpAttantion: false # 设置为 true 或 false，用于控制 --enable-dp-attention
  dp: 1 # 已被sglang弃用，但如果需要传递该参数，请确保其逻辑正确
  torchCompile: false # 设置为 true 或 false，用于控制 --enable-torch-compile
  torchCompileMaxBs: 8      # 最大批量大小 
  # Leader 专用参数
  leader:
    port: 40000
  # 网络配置（用于worker与leader通信）
  distInitPort: 20000
  #deepseek
  enableEpMoe: false # 设置为 true 或 false
  enableDeepepMoe: false # 设置为 true 或 false
  enableEplb: false      # ep负载均衡，设置为 true 或 false
  ep: 1  # ep并行，对应 --ep-size 或相关参数
  enableDpAttention: false # deepseek dp attention

commandStr: |
  python3 -m sglang.launch_server \
    --model-path /{{ .Values.model.name }} \
    --mem-fraction-static "{{ .Values.llmConfig.memFractionStatic }}" \
    --tp "{{ .Values.llmConfig.tp }}" \
    --dist-init-addr $(LWS_LEADER_ADDRESS):{{ .Values.llmConfig.distInitPort }} \
    --nnodes $(LWS_GROUP_SIZE) \
    --node-rank $(LWS_WORKER_INDEX) \
    --trust-remote-code \
    --host 0.0.0.0 \
    --port "{{ .Values.llmConfig.leader.port }}" \
    {{- if .Values.llmConfig.dpAttantion }}
    --enable-dp-attention \
    {{- end }}
    {{- if .Values.llmConfig.torchCompile }}
    --enable-torch-compile \
    --torch-compile-max-bs "{{ .Values.llmConfig.torchCompileMaxBs }}" \
    {{- end }}
    {{- if .Values.llmConfig.dp }}
    --dp "{{ .Values.llmConfig.dp }}" \
    {{- end }}
    {{- if .Values.llmConfig.enableEpMoe }}
    --enable-ep-moe \
    --ep-size "{{ .Values.llmConfig.ep }}" \
    {{- end }}
    {{- if .Values.llmConfig.enableDeepepMoe }}
    --enable-deepep-moe \
    {{- end }}
    {{- if .Values.llmConfig.enableEplb }}
    --enable-eplb \
    {{- end }}


# 网络配置
network:
  hostNetwork: true
  hostIPC: true
  dnsPolicy: ClusterFirstWithHostNet

# 服务配置
service:
  enabled: true
  name: llm-service-endpoint
  type: LoadBalancer
  port: 40000
  targetPort: 40000


# 环境变量
env:
  # NCCL/RDMA配置
  ncclIBCudaSupport: 1
  ncclIBDisable: 0
  ncclIbGidIndex: 3
  ncclSocketIfname: eth0
  ncclDebug: INFO
  # gloo
  glooSocketIfname: eth0

envStr: |
  - name: NCCL_IB_CUDA_SUPPORT
    value: "{{ .Values.env.ncclIBCudaSupport }}"
  - name: NCCL_IB_DISABLE
    value: "{{ .Values.env.ncclIBDisable }}"
  - name: NCCL_IB_GID_INDEX
    value: "{{ .Values.env.ncclIbGidIndex }}"
  - name: NCCL_DEBUG
    value: "{{ .Values.env.ncclDebug }}"
  - name: GLOO_SOCKET_IFNAME
    value: "{{ .Values.env.glooSocketIfname }}"
  - name: NCCL_SOCKET_IFNAME
    value: "{{ .Values.env.ncclSocketIfname }}"

volumes: |
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: {{ .Values.resourcesPerNode.sharedMemory }}
  - name: ib
    hostPath:
      path: /dev/infiniband
  {{- if .Values.model.pvc.enabled }}
  - name: model
    persistentVolumeClaim:
      claimName: {{ .Values.model.pvcName }}
  {{- else if .Values.model.local.enabled }}
  - name: model
    hostPath:
      path: {{ .Values.model.local.path }}
  {{- end }}


volumeMounts: | 
  - name: dshm
    mountPath: /dev/shm  
  - name: ib
    mountPath: /dev/infiniband
  {{- if .Values.model.pvc.enabled }}
  - name: model
    mountPath: /{{ .Values.model.name }}
    subPath: {{ .Values.model.pvc.path }}
  {{- else if .Values.model.local.enabled }}
  - name: model
    mountPath: /{{ .Values.model.name }}
  {{- end }}


ResourcesStr: |
  limits:
    nvidia.com/gpu: "{{ .Values.resourcesPerNode.gpu }}"
    cpu: "{{ .Values.resourcesPerNode.cpu }}"
    memory: "{{ .Values.resourcesPerNode.memory }}"
  requests:
    nvidia.com/gpu: "{{ .Values.resourcesPerNode.gpu }}"
    memory: "{{ .Values.resourcesPerNode.memory }}"

securityContext:
  privileged: true

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbeStr: |
  httpGet:
    path: /health
    port: {{ .Values.llmConfig.leader.port }}
  initialDelaySeconds: 60
  failureThreshold: 80
  periodSeconds: 30
  timeoutSeconds: 5

readinessProbeStr: |
  httpGet:
    path: /health
    port: {{ .Values.llmConfig.leader.port }}
  initialDelaySeconds: 60
  failureThreshold: 80
  periodSeconds: 30
  timeoutSeconds: 5

startupProbe: |
  httpGet:
    path: /health
    port: {{ .Values.llmConfig.leader.port }}
  initialDelaySeconds: 20
  failureThreshold: 30  # 30次
  periodSeconds: 30
  timeoutSeconds: 5